name: quadritech
description: A new Flutter project.


publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.1.0
  firebase_auth: ^3.0.1
  cloud_firestore: ^3.1.14
  firebase_storage: ^10.0.1
  image_picker: ^0.8.3+1
  intl: ^0.17.0
  get:
  camera: ^0.10.0+3
  video_compress: ^3.1.1
  url_launcher: ^6.1.6
  video_thumbnail: ^0.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/